export const CONFIG = {
    BASE_URL: process.env.NEXT_PUBLIC_BASE_URL,
    GITHUB_URL: process.env.NEXT_PUBLIC_GITHUB_URL,
    GITHUB_TOKEN: process.env.NEXT_PUBLIC_GITHUB_TOKEN,
    OWNER_NAME: process.env.NEXT_PUBLIC_OWNER_NAME,
    REPO_NAME: process.env.NEXT_PUBLIC_REPO_NAME,
    BRANCH_NAME: process.env.NEXT_PUBLIC_BRANCH_NAME,
    REPO_WITH_OWNER: process.env.NEXT_PUBLIC_REPO_WITH_OWNER
}